[server]
# 监听端口，用于接收来自发送端的连接
listen_port = 10000
# 注入IP，用于将流量注入到本地回环接口
inject_ip = 127.0.0.1

[logging]
# 日志文件路径: /var/log/traptunnel/receiver.log
# 日志文件最大大小，单位MB
max_log_size = 10
# 最大日志备份数    
max_log_backups = 100

[nodes]
# 节点ID，用于标识接收端
1 = HSH
2 = HY
3 = SD
