[common]
node_id = 1

# 新配置方式：支持多个服务器 (逗号分隔)
# 格式: ip:port, ip:port
servers = 215.1.194.73:10000

[advanced]
listen_port = 162
reconnect_interval = 5
max_buffer_size = 2000

[logging]
log_file = sender.log
max_log_size = 10
max_log_backups = 100
