[common]
# 节点ID，用于标识发送端
node_id = 1

# 多目标配置方式: ip1:port, ip2:port
servers = 215.1.194.73:10000

[advanced]
# 监听端口，用于接收来自接收端的连接
listen_port = 162
# 重连间隔，单位秒
reconnect_interval = 5
# 最大缓冲区大小，单位字节
max_buffer_size = 2000

[logging]
# 日志文件路径: /var/log/traptunnel/sender.log
# 日志文件最大大小，单位MB
max_log_size = 10
# 最大日志备份数
max_log_backups = 100
